### ISSUE TITLE
Branch selection does not work

### ISSUE THREAD

**Issue by andreypz** [cms-nanoAOD/nanoAOD-tools#100]
According to the readme file the following command should skim input tree and drop/keep various branches:
```
python scripts/nano_postproc.py outDir f.root -b keep_and_drop.txt
```
From my tests this does not work - branches are not dropped.

**Comment by andreypz** [comment]
Also not working another example from readme:

```
[andreypz@lx3a60 NanoAODTools]$ python scripts/nano_postproc.py outDir f.root -I PhysicsTools.NanoAODTools.postprocessing.examples.mhtProducer mht
Traceback (most recent call last):
  File "scripts/nano_postproc.py", line 34, in <module>
    import_module(mod)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/lib64/python2.7/site-packages/ROOT.py", line 461, in _importhook
    return _orig_ihook( name, *args, **kwds )
ImportError: No module named mhtProducer
```

**Comment by arizzi** [comment]
Thanks for reporting the problem.

In fact while the core should work, many of the implemented modules  needs CMSSW because some calibration libraries are not available as standalone.

Concerning the keep and drop was also reported by others in the past days and I think it could be that it was broken when the drop/keep was separated for input and output.

We should probably update the command line version and/or the documentation.

**Comment by andreypz** [comment]
Ok, the second part work after switching under CMSSW.

As for drop/keep part, do you have a suggestion how to fix that. Perhaps there is another way to drop the branches, otherwise how do you make skim ntuples?

Also, do you know of any analysis (in github) which use these nanoaod-tools to run? I've seen people using the NanoAod ntuples, but not the NanoAod-tools...

**Comment by arizzi** [comment]
see for example
https://twiki.cern.ch/twiki/bin/viewauth/CMS/VHiggsBB#Get_the_ntuplizer_software
the "Postprocessor" part

**Comment by arizzi** [comment]
can you try adding at line
https://github.com/cms-nanoAOD/nanoAOD-tools/blob/master/scripts/nano_postproc.py#L45
an additional parameter
outputbranchsel= options.branchSel

i.e. force it to use the same branch selection in input and output ?

**Comment by andreypz** [comment]
Indeed, that fix works, thanks.

However it's not clear to me what is the purpose of the _input_ keep/drop file?
Is it done to read the tree faster when dropping some branches? Testing this a bit - it is not the case...

**Comment by arizzi** [comment]
you may want to replace a branch so you drop in input Jet_pt and you create
in your modules a new Jet_pt (hence you do not drop it on output)
