### ISSUE TITLE
"Counting histograms" for event/genWeight counts

### ISSUE THREAD

**Issue by davignon** [cms-nanoAOD/nanoAOD-tools#120]
In the process of designing the analysis, I implemented one feature that I think would fit well into NanoAOD-tools.
When performing cross section weighting of the MC, one needs to know the number of events (or, more generally, the sum of genWeights) in the generated sample (i.e. before selection).

To have this information kept after NanoAOD-tools processing, we created a root TH1 within NanoAOD-tools, see:
https://github.com/vukasinmilosevic/nanoAOD-tools/blob/master/python/postprocessing/framework/eventloop.py#L50
That we fill in this way:
- Bin 1: sum of weights
- Bin 2: sum of weights for events that have genWeight >= 0
- Bin 3: sum of weights for events that have genWeight < 0
- Bin 4: sum of weights for events that pass the selection implemented within NanoAOD-tools.
The filling is done there:
https://github.com/vukasinmilosevic/nanoAOD-tools/blob/master/python/postprocessing/framework/eventloop.py#L63
There is one histogram per root file produced, written here:
https://github.com/vukasinmilosevic/nanoAOD-tools/blob/master/python/postprocessing/framework/eventloop.py#L92

If several jobs are used to process one sample (as is usually the case), hadd'ing the output root files would hadd the trees as well as the histograms, that will then still be suitable for XS weighting.

Advantages of the method:
1) It is completely transparent to users that wouldn't want to use the feature.
2) It doesn't take a lot of disk space (histogram is very light).
3) It's useful to XS-weight the sample, but also to know the efficiency of the selection & the fraction of events with negative weights.

This is I think related to issue #28.

@arizzi, in an email discussion with me, you mentioned some potential problem with this method clashing with pre-filtering (i.e. when using pre-filtering, we would understandably get unreliable estimates for the sum of weights). You also mentioned a potential way around this. Can you please tell us more?

Thanks in advance, cheers,
- Olivier

**Comment by arizzi** [comment]
@gpetruc @peruzzim  it seems we have a problem with e.g.

*Br    5 :LHEScaleSumw :                                                     *
*         | Double_t Sum of genEventWeight * LHEScaleWeight[i], divided by genEventSumw*

the division by "genEvenSumw" makes it unusable when multiple inputs are processed in merging step (I've to admit it is not fully clear to me when things are summed and when are appended)

@davignon can you anyhow clarify which use case you were not able to cover with the Run tree content?

**Comment by davignon** [comment]
@arizzi 
Thanks.

I think what you are describing is exactly the problem we had: we are processing a dataset through multiple jobs and get multiple output root files, so any branch which `xs_weights`'s value only depends on the event or the (local) tree is not usable to perform XS-reweighting. Ideally we would like to have a unique number (e.g. sum of weights) for each dataset. Counting Histograms are a way to achieve that; I don't know if branches could work as they are event-by-event and selections are applied at NanoAOD-tools level.

Some side comment: I couldn't find mention of `genEventWeight` in the trees, nor in the doc:
https://cms-nanoaod-integration.web.cern.ch/integration/master-102X/mc102X_doc.html

Cheers,
- Olivier

**Comment by arizzi** [comment]
@davignon right, it seems we are lacking some docs for the Run and Lumi trees. The doc you mention is the one autogenerated for the Event tree.

There is an additional Run Tree that contains the info you need, in principle  you need to sum over the entries you find there and should obtain the same results as from your count histos.
Can you cross-check?

Then some docs should be added in the twiki...

**Comment by arizzi** [comment]
was the xchecl successful? if so can we close this?

**Comment by davignon** [comment]
@arizzi ,
I haven't fully tested it, but judging by the consistency of the numbers in our histograms and the "Runs" tree, I don't see any reason why it shouldn't work.
So we can close this. Thanks again for your help.
