### ISSUE TITLE
Prefiring module

### ISSUE THREAD

**Issue by DennRoy** [cms-nanoAOD/nanoAOD-tools#136]
Hi,
as mentioned in the previous CrossPOG meeting, here is a module that computes the prefire weights:
https://github.com/latinos/LatinoAnalysis/blob/master/NanoGardener/python/modules/PrefireCorr.py
Aside from the paths pointing to the maps, I think it should work out-of-the-box. Can you please let me know, if there are any changes I should make?

**Comment by adewit** [comment]
Hi,
I'm not one of the central developers, but it's probably easiest if you can make a pull request into this repository to include the module and the maps. Then if someone has comments on things in the code they can comment directly on the diff.
For what it's worth, I picked up the module you link above and it did seem to work out of the box after changing the paths pointing to the maps.

**Comment by DennRoy** [comment]
Thanks, I made a PR here:
#139
