### ISSUE TITLE
NanoGEN

### ISSUE THREAD

**Issue by nsmith-** [cms-nanoAOD/nanoAOD-tools#144]
I think it would be really useful for many people to be able to easily (e.g. via cmsDriver) add a NanoAOD-like output starting from the GEN data tier, for MC studies.  One would have access to all the nice gen additions included in the current NanoAOD, and any already-produced samples could easily be compared to newly generated samples, which can be made privately quite easily without the necessity for the whole SIM-DIGI-RECO-AOD-MINIAOD chain.
To do this, we just need to separate the gen-only portions of `nanoSequenceMC` from those that require reconstructed objects.  I made a first attempt to remove any reco-related tables and redirect the input sources when they differ.

```python
# Hacking at nanoSequenceMC from PhysicsTools.NanoAOD.nano_cff
process.jetMC.remove(process.jetMCTable)
process.nanogenSequence = cms.Sequence(
    process.genParticleSequence+
    process.genParticles2HepMC+
    process.particleLevel+
    process.genJetTable+
    process.patJetPartons+
    process.genJetFlavourAssociation+
    process.genJetFlavourTable+
    process.genJetAK8Table+
    process.genJetAK8FlavourAssociation+
    process.genJetAK8FlavourTable+
    process.tauGenJets+
    process.tauGenJetsSelectorAllHadrons+
    process.genVisTaus+
    process.genVisTauTable+
    process.genTable+
    process.genWeightsTable+
    process.genParticleTables+
    process.particleLevelTables+
    process.lheInfoTable
)
process.finalGenParticles.src = cms.InputTag("genParticles")
process.genParticles2HepMC.genParticles  = cms.InputTag("genParticles")
process.patJetPartons.particles = cms.InputTag("genParticles")

process.genJetTable.src = cms.InputTag("ak4GenJetsNoNu")
process.genJetFlavourAssociation.jets = process.genJetTable.src
process.genJetFlavourTable.src = process.genJetTable.src
process.genJetFlavourTable.jetFlavourInfos = cms.InputTag("genJetFlavourAssociation")
process.genJetAK8Table.src = cms.InputTag("ak8GenJetsNoNu")
process.genJetAK8FlavourAssociation.jets = process.genJetAK8Table.src
process.genJetAK8FlavourTable.src = process.genJetAK8Table.src
process.tauGenJets.GenParticles = cms.InputTag("genParticles")
process.genVisTaus.srcGenParticles = cms.InputTag("genParticles")
```

**Comment by nsmith-** [comment]
More details: I started with `cmsDriver.py myNanoProdMc -s NANO --mc --eventcontent NANOAODSIM --datatier NANOAODSIM --no_exec --conditions auto:run2_mc` from the [TWiki](https://twiki.cern.ch/twiki/bin/view/CMSPublic/WorkBookNanoAOD#Running_on_various_datasets_from) and added the above lines, then edited `process.nanoAOD_step = cms.Path(process.nanogenSequence)`

**Comment by peruzzim** [comment]
This is a nice idea, I would support that, but this issue should be opened under cms-nanoAOD/cms-sw, not in the tools repository. Please reopen there so we can discuss the implementation.
