### ISSUE TITLE
Wrong corrected jet pT passed to JetUncertainty in JetReCalibrator?

### ISSUE THREAD

**Issue by suyong-choi** [cms-nanoAOD/nanoAOD-tools#145]
I was just browsing the code to see what was done and found a strange calculation of corrected jet pT

https://github.com/cms-nanoAOD/nanoAOD-tools/blob/acf2e055a37de3d61d92e962d2f350077638feb7/python/postprocessing/modules/jme/JetReCalibrator.py#L72

I would expect the following would be the correct way:

self.JetUncertainty.setJetPt(corr * jet.pt() * (1.0 - jet.rawFactor()))

**Comment by fgolf** [comment]
Fixed by PR #182.
