### ISSUE TITLE
Groomed mass needs to be corrected by PUPPI SD mass correction before applying mass scaling and smearing

### ISSUE THREAD

**Issue by lcorcodilos** [cms-nanoAOD/nanoAOD-tools#156]
In relation to issue #150 and #151.

I don't believe the PUPPI SD mass correction detailed here [1] is ever applied before calculating the JMS and JMR corrections. According to this procedure [2], this is incorrect.

[1] - https://github.com/cms-jet/PuppiSoftdropMassCorr
[2] - https://twiki.cern.ch/twiki/bin/view/Sandbox/PUPPIJetMassScaleAndResolution

**Comment by fgolf** [comment]
Fixed by PR #167
