### ISSUE TITLE
jet_m_resolution variable undefined in jetSmearer.py

### ISSUE THREAD

**Issue by camclean** [cms-nanoAOD/nanoAOD-tools#161]

**Comment by eshwen** [comment]
Also having this issue. Is someone able to resolve it?

**Comment by benkrikler** [comment]
It seems this has been there since PR #48 when the new functionality was first added by @rappoccio.

**Comment by camclean** [comment]
Should be solved by PR #166

**Comment by fgolf** [comment]
This issue is fixed by PR #167
