### ISSUE TITLE
Smear with corrected or uncorrected pt?

### ISSUE THREAD

**Issue by IzaakWN** [cms-nanoAOD/nanoAOD-tools#164]
In [this line](https://github.com/cms-nanoAOD/nanoAOD-tools/blob/master/python/postprocessing/modules/jme/jetmetUncertainties.py#L284),
```
... = self.jetSmearer.getSmearValsPt(jet, genJet, rho)
```
the pt of the `jet` object has not been corrected to `jet_pt` (in case it is recalibrated). Should the smearing be done based on the recalibrated jet pt? In that case, one should add
```
jet.pt = jet_pt
... = self.jetSmearer.getSmearValsPt(jet, genJet, rho)
```

**Comment by IzaakWN** [comment]
@camclean, do you know?

**Comment by camclean** [comment]
Hi @IzaakWN, you're right. Thanks for catching that! And same for the mass.

**Comment by camclean** [comment]
I just made a PR. (#170)
