### ISSUE TITLE
genEventCount and genEventsSumW in nanoAOD

### ISSUE THREAD

**Issue by alefisico** [cms-nanoAOD/nanoAOD-tools#171]
Hi all,
Sorry for the basic question, but I think I dont understand the values stored in the Runs tree in nanoAOD or how should I use this information to normalize my samples. For instance I am looking at this dataset:
`/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8/RunIIAutumn18NanoAODv4-Nano14Dec2018_102X_upgrade2018_realistic_v16-v1/NANOAODSIM`
and in one of the files (`/store/mc/RunIIAutumn18NanoAODv4/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8/NANOAODSIM/Nano14Dec2018_102X_upgrade2018_realistic_v16-v1/120000/19A124F7-223F-554D-BE45-2A732FA28437.root`) a Runs->Scan() prints:
```
*    Row   * Instance *       run * genEventC * genEventS * genEventS * nLHEScale * LHEScaleS * nLHEPdfSu * LHEPdfSum *
***********************************************************************************************************************
*        0 *        0 *         1 *   1750000 * 526471551 * 1.609e+11 *         9 * 28.156499 *        33 * 25.287363 *
```
while other file (`/store/mc/RunIIAutumn18NanoAODv4/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8/NANOAODSIM/Nano14Dec2018_102X_upgrade2018_realistic_v16-v1/120000/89AB8594-E988-8243-834C-C6E88AD4F2C7.root`) gives me this:
```
*    Row   * Instance *       run * genEventC * genEventS * genEventS * nLHEScale * LHEScaleS * nLHEPdfSu * LHEPdfSum *
***********************************************************************************************************************
*        0 *        0 *         1 *   1350000 * 406089795 * 1.241e+11 *         9 * 30.416809 *        33 * 27.313344 *
```
Then, the dataset has to normalized to sum all the genEventCounts in each file? What exactly are the genEventSumW and genEventSumW2? Is there any place where this is documented?
Thanks for the help

**Comment by peruzzim** [comment]
Yes, you should sum over the entries of the run tree.
And the genEventSumW and genEventSumW2 are just the sum of weights and weights squared of the events, as it's written in the branch title string.
