### ISSUE TITLE
L1 trigger information is not available 

### ISSUE THREAD

**Issue by vardanaloyan** [cms-nanoAOD/nanoAOD-tools#173]
Hello. I want to access L1 trigger (L1_TripleJet_100_85_72_VBF) in my analysis but i have such error message 

if not branch: raise RuntimeError, "Unknown branch %s" % branchName
RuntimeError: Unknown branch L1_TripleJet_100_85_72_VBF

i accessed by this way: getattr(event, L1_TripleJet_100_85_72_VBF, False)

Dataset is: dataset=/VBFHToBB_M-125_13TeV_powheg_pythia8_weightfix/RunIIFall17NanoAODv4-PU2017_12Apr2018_Nano14Dec2018_102X_mc2017_realistic_v6-v1/NANOAODSIM

I have also downloaded the root-files of this dataset, and opened it on TBrowser, but there are not these (L1_*) branches. But in documentation it mentioned that, there will be this branches...

Documentation: https://cms-nanoaod-integration.web.cern.ch/integration/master-102X/mc94X_doc.html#L1

Thanks in advance!
Vardan Aloyan

**Comment by AndreasAlbert** [comment]
The dataset you tried if from the "v4" campaign, which does not correspond to the documentation you are looking at. Try the sample from the "v5" campaign, e.g. by searching dataset=/VBFHToBB_M-125_13TeV_powheg_pythia8_weightfix/RunIIFall17NanoAODv5*1Jun*/NANOAODSIM

**Comment by vardanaloyan** [comment]
Thanks I can handle L1 trigger information.
