### ISSUE TITLE
NANOAOD Json good run list

### ISSUE THREAD

**Issue by vardanaloyan** [cms-nanoAOD/nanoAOD-tools#175]
Hello everyone. I want to do preselection of /BTagCSV/Run2017F-31Mar2018-v1/NANOAOD dataset, using the good run list text file. I saw that postprocessor has a parameter called inputJson, i gave this parameter but get the error`
Error in <TTreeFormula::Compile>:  Empty String
Info in <TSelectorDraw::AbortProcess>: Variable compilation failed: {,() && (305405 <= run && run <= 306460)}
``````````````````````````
I used condor for it.

Can you give me instructions for it.
Thanks in advance!

**Comment by fgolf** [comment]
@vardanaloyan Can you send the config you're trying to run?

**Comment by fgolf** [comment]
@vardanaloyan did you resolve your issue?

**Comment by vardanaloyan** [comment]
yes it is solved
