### ISSUE TITLE
 "v5" campaign QCD_HT* NANOAODs needed

### ISSUE THREAD

**Issue by vardanaloyan** [cms-nanoAOD/nanoAOD-tools#178]
Hello everyone. I need  "v5" campaign NANOAOD datasets of these 3 MINIAOD datasets:

1) /QCD_HT300to500_TuneCP5_13TeV-madgraph-pythia8/RunIIFall17MiniAODv2-PU2017_12Apr2018_new_pmx_94X_mc2017_realistic_v14-v1/MINIAODSIM
2) /QCD_HT700to1000_TuneCP5_13TeV-madgraph-pythia8/RunIIFall17MiniAODv2-PU2017_12Apr2018_new_pmx_94X_mc2017_realistic_v14-v2/MINIAODSIM
3) /QCD_HT1000to1500_TuneCP5_13TeV-madgraph-pythia8/RunIIFall17MiniAODv2-PU2017_12Apr2018_new_pmx_94X_mc2017_realistic_v14-v1/MINIAODSIM

There is child nanoaod datasets, but there are v4 campaign, I need v5, with L1 trigger information.
Thanks in advance!

**Comment by fgolf** [comment]
Similar comments as issue #177. Closing.
