### ISSUE TITLE
ImportError: cannot import name InputTree

### ISSUE THREAD

**Issue by alefisico** [cms-nanoAOD/nanoAOD-tools#196]
Hi all

Without changing anything in my NanoAODTools package, since yesterday I started getting errors like:
```
Traceback (most recent call last):
  File "evenSimplerJob_nanoAODPostproc.py", line 15, in <module>
    from PhysicsTools.NanoAODTools.postprocessing.framework.postprocessor import PostProcessor
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc700/lcg/root/6.12.07-gnimlf5/lib/ROOT.py", line 318, in _importhook
    return _orig_ihook( name, *args, **kwds )
  File "/afs/cern.ch/work/a/algomez/ttH/CMSSW_10_2_15/python/PhysicsTools/NanoAODTools/postprocessing/framework/postprocessor.py", line 9, in <module>
    from PhysicsTools.NanoAODTools.postprocessing.framework.datamodel import InputTree
ImportError: cannot import name InputTree
```
I am working on lxplus, CMSSW_10_2_15, and after the first error I pull the latest changes from master. Does anyone have an idea what is the error about?

**Comment by fgolf** [comment]
I was not able to reproduce the problem running a few modules in the same release.  Can you please provide more information?

**Comment by alefisico** [comment]
Hi, thanks for looking into this. 
I dont know what happened but today, I cloned again the NanoAODTools package, I recompiled CMSSW and I dont have the problem anymore. 
I dont understand what happened since I recompiled CMSSW before and pull the package. What I did new is remove the package completely and cloned it. 
In any case, thanks for the help.
