### ISSUE TITLE
btagSF DeepJet (or DeepFlavour) not yet fully included

### ISSUE THREAD

**Issue by NikHoffStyl** [cms-nanoAOD/nanoAOD-tools#209]
https://github.com/cms-nanoAOD/nanoAOD-tools/blob/5f6b62da3a0e9d16bedbf28069d9bb653768f032/python/postprocessing/modules/btv/btagSFProducer.py#L166
DeepJet option is available in dictionary, but Lines 158-167 and 311-319 in btagSFProducer.py need it added here; otherwise it would raise an error.

**Comment by NJManganelli** [comment]
While the variable references DeepFlavour, perhaps the algo reference should use the real name (to be used in publication):
[HN](https://hypernews.cern.ch/HyperNews/CMS/get/btag/1654.html)

**Comment by fgolf** [comment]
@NikHoffStyl  Thanks for reporting this.  The issue should be fixed by PR #212.
