### ISSUE TITLE
MET and (Fat)Jet JME uncertaintes in data with jetmetHelperRun2.py

### ISSUE THREAD

**Issue by bartokm** [cms-nanoAOD/nanoAOD-tools#210]
When using the createJMECorrector function with data there are no Up/Down fluctuation variables saved in the tree. I see in [jetmetUncertainties.py](https://github.com/cms-nanoAOD/nanoAOD-tools/blob/master/python/postprocessing/modules/jme/jetmetUncertainties.py) that it is saved only when isData=False. The JES uncertainties for jets, and the JES and UES uncertainties for MET should be saved for data as well. If not, why, and what is the recommended way for calculating them?

**Comment by fgolf** [comment]
Variations (for evaluation of uncertainties) are only performed for simulation, not data.  Closing.
