### ISSUE TITLE
A question about MET_{pt,phi}_jer and METFixEE2017_{pt,phi}_jer

### ISSUE THREAD

**Issue by pieterdavid** [cms-nanoAOD/nanoAOD-tools#221]
While going through the Type-1 MET correction / variations code, I noticed that the METFixEE2017 recipe modifies all MET variations (nominal, JEC uncertainties, etc.) by the same amount, and also the smeared MET variations (jerUp, jerDown) but not the nominal smeared MET (`METFixEE2017_{pt,phi}_jer`) value (see [here](https://github.com/cms-nanoAOD/nanoAOD-tools/blob/master/python/postprocessing/modules/jme/jetmetUncertainties.py#L442-L455)).
Is this intentional? I'm not an expert, but at first sight it looks inconsistent to me (and might, if the correction is sizeable, give a strongly asymmetric JER uncertainty, i.e. jerUp-jer and jer-jerDown).
Also - apologies for my ignorance - should one then use either `MET_{pt,phi}_nom` with the JES variations (Type-1) and include no smearing, or use the smeared `MET_{pt,phi}_jer{,Up,Down}` and ignore JES uncertainties (because the central values are different)? For the jets the nominal includes both the JEC and smearing (if applicable) and the variations are with respect to that, so they can be combined - I am wondering how to propagate the uncertainties to quantities that depend both on the MET and jet momenta.
Thanks in advance

**Comment by danbarto** [comment]
Hi @pieterdavid, thanks for pointing that out and sorry for the delayed answer. The central JER smeared value should indeed also be corrected with the v2 factor.

**Comment by pieterdavid** [comment]
Thanks @danbarto for the confirmation and fix!
