### ISSUE TITLE
New 2016 FastSim JEC available

### ISSUE THREAD

**Issue by bartokm** [cms-nanoAOD/nanoAOD-tools#224]
There is new 2016 FastSim JEC available in https://twiki.cern.ch/twiki/bin/view/CMS/JECDataMC (Summer16_FastSimV1_MC), can you please update this?
It's need to be added here: https://github.com/cms-nanoAOD/nanoAOD-tools/tree/master/data/jme
And change the string here: https://github.com/cms-nanoAOD/nanoAOD-tools/blob/master/python/postprocessing/modules/jme/jetmetHelperRun2.py#L13

**Comment by fgolf** [comment]
@bartokm can you make a PR with these changes?

**Comment by bartokm** [comment]
I've tried this locally, and I get this error message:
"No definitions found!!!"
Maybe something else is also needed? I'm not really a nanoAOD expert...

**Comment by danbarto** [comment]
Hi @bartokm, the problem occurs because there's a subdirectory inside the provided tarball. I just opened a PR containing the correct tarball.

**Comment by bartokm** [comment]
Thank you @danbarto! I tested the new tarball locally it works. In the PR shouldn't you also change the [jetmetHelperRun2](https://github.com/cms-nanoAOD/nanoAOD-tools/blob/master/python/postprocessing/modules/jme/jetmetHelperRun2.py#L13)?

**Comment by danbarto** [comment]
You are absolutely right, this change got lost somehow. I just updated the PR.
