### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by jeffkrupa** [cms-nanoAOD/nanoAOD-tools#246]
Hi, is there any plan or developmental branch for adding py3 support for nanoaod-tools ?

**Comment by mariadalfonso** [comment]
we do not have in the works
do you want to help in the migration ?
this task will be reworded with EPR

**Comment by Laurits7** [comment]
> we do not have in the works
> do you want to help in the migration ?
> this task will be reworded with EPR

Hey, if there are no volunteers, then I would be possibly interested in the task. I guess it would be a great moment to synchronize the coding style across the whole project (pep8 and the scram code-checks for c++).

**Comment by mariadalfonso** [comment]
Hi @Laurits7

This is great, this topic is all yours. Please start and keep us posted on the progress.

**Comment by mariadalfonso** [comment]
work done in 
https://github.com/cms-nanoAOD/nanoAOD-tools/pull/251
