### ISSUE TITLE
Unclustered energy variations on T1Smear MET

### ISSUE THREAD

**Issue by alpakpinar** [cms-nanoAOD/nanoAOD-tools#259]
As PR #244 is merged, the JME uncertainty module calculates and saves uncertainties for T1 and T1Smear MET separately. This is being done for JES/JER uncertainties, but the unclustered energy variations remain untouched, they are calculated only for T1 MET in [1], but not for T1Smear MET. I believe this is causing two issues:

1. Unclustered energy variations are no longer applicable to use for analyses where smearing corrections are used.

2. A new naming scheme is introduced for the branches where JES/JER uncs are saved, but the branch names for unclustered energy ones remain as in the old version, which might cause additional confusion.

Can we make this calculation for T1 and T1Smear MET separately, and save them separately, as we're now doing with JES/JER uncertainties? I can also prepare a PR for this as well, thank you!

[1]: https://github.com/cms-nanoAOD/nanoAOD-tools/blob/master/python/postprocessing/modules/jme/jetmetUncertainties.py#L859-L869

**Comment by andreypz** [comment]
It does cause confusion! Also because the naming is different with respect to the previous version of the tool, which we used in our analysis.
So, do I understand correctly that the current version of the code would give wrong uncertainties for T1Smear MET?

**Comment by alpakpinar** [comment]
Yes, the naming is unfortunately quite different from earlier. I think except the unclustered energy uncertainties, uncertainties on T1 and T1Smear MET should be calculated correctly. With the current version of the code, I believe unclustered energy uncertainties are calculated correctly for T1 MET but not for T1Smear MET.

**Comment by pieterdavid** [comment]
Since I'm not sure if linking a PR triggers a notification by itself: after the discussion in https://github.com/cms-nanoAOD/nanoAOD-tools/pull/256 I implemented what I think is the changed discussed above, please have a look at https://github.com/cms-nanoAOD/nanoAOD-tools/pull/266
