### ISSUE TITLE
Histograms with event counts before cuts are applied

### ISSUE THREAD

**Issue by veelken** [cms-nanoAOD/nanoAOD-tools#28]
Hi,

I think it will be of general interest to add histograms that keep tracks of the event counts before skimming cuts are applied, similar to what we had in the VHbb Ntuples/heppy:
        "Count",
        "CountFullWeighted",
        "CountWeighted",
        "CountPosWeight",
        "CountNegWeight",
        "CountWeightedLHEWeightScale",
        "CountWeightedLHEWeightPdf",

I can write this code, but would need an example how to book and fill a histogram in the nanoAOD-tools output file.

Cheers,

Christian

**Comment by arizzi** [comment]
most of those are covered accessing the run products from the Run tree filled here:
https://github.com/cms-nanoAOD/cmssw/blob/master/PhysicsTools/NanoAOD/plugins/GenWeightsTableProducer.cc#L379-L390

**Comment by arizzi** [comment]
<pre>
root [2] Runs->Print()
******************************************************************************
*Tree    :Runs      : Runs                                                   *
*Entries :        1 : Total =            5252 bytes  File  Size =       1470 *
*        :          : Tree compression factor =   1.00                       *
******************************************************************************
*Br    0 :run       : run/i                                                  *
*Entries :        1 : Total  Size=        540 bytes  File Size  =         74 *
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *
*............................................................................*
*Br    1 :genEventCount : Long64_t event count                               *
*Entries :        1 : Total  Size=        598 bytes  File Size  =         88 *
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *
*............................................................................*
*Br    2 :genEventSumw : Double_t sum of gen weights                         *
*Entries :        1 : Total  Size=        601 bytes  File Size  =         87 *
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *
*............................................................................*
*Br    3 :genEventSumw2 : Double_t sum of gen (weight^2)                     *
*Entries :        1 : Total  Size=        608 bytes  File Size  =         88 *
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *
*............................................................................*
*Br    4 :nLHEScaleSumw : UInt_t Number of entries in LHEScaleSumw           *
*Entries :        1 : Total  Size=        608 bytes  File Size  =         84 *
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *
*............................................................................*
*Br    5 :LHEScaleSumw :                                                     *
*         | Double_t Sum of genEventWeight * LHEScaleWeight[i], divided by genEventSumw*
*Entries :        1 : Total  Size=        761 bytes  File Size  =         91 *
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *
*............................................................................*
*Br    6 :nLHEPdfSumw : UInt_t Number of entries in LHEPdfSumw               *
*Entries :        1 : Total  Size=        598 bytes  File Size  =         82 *
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *
*............................................................................*
*Br    7 :LHEPdfSumw :                                                       *
*         | Double_t Sum of genEventWeight * LHEPdfWeight[i], divided by genEventSumw*
*Entries :        1 : Total  Size=        745 bytes  File Size  =         89 *
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.00     *
*............................................................................*
root [3] Runs->Scan()
***********************************************************************************************************************
*    Row   * Instance *       run * genEventC * genEventS * genEventS * nLHEScale * LHEScaleS * nLHEPdfSu * LHEPdfSum *
***********************************************************************************************************************
*        0 *        0 *         1 *    135731 * 135745.61 * 135761.24 *         0 *           *         0 *           *
***********************************************************************************************************************

</pre>
