### ISSUE TITLE
Errors with 12_3_X 

### ISSUE THREAD

**Issue by michael-pitt** [cms-nanoAOD/nanoAOD-tools#295]
The following sequence is working:
```
cmsrel CMSSW_10_6_27
cd CMSSW_10_6_27/src
cmsenv
git clone https://github.com/cms-nanoAOD/nanoAOD-tools.git PhysicsTools/NanoAODTools
cd PhysicsTools/NanoAODTools
scram b
python scripts/nano_postproc.py
```

The next one throwing `ImportError: No module named PhysicsTools.NanoAODTools.postprocessing.framework.postprocessor`
```
cmsrel CMSSW_12_3_0_pre1
cd CMSSW_12_3_0_pre1/src
cmsenv
git clone https://github.com/cms-nanoAOD/nanoAOD-tools.git PhysicsTools/NanoAODTools
cd PhysicsTools/NanoAODTools
scram b
python scripts/nano_postproc.py
```

I'm trying to run the nanoAOD production with the recent release.

**Comment by sroychow** [comment]
Hi @michael-pitt , I think this has to do with python version. Can you try:-
```
python3 scripts/nano_postproc.py
```

**Comment by michael-pitt** [comment]
Hi @sroychow, Thanks! new errors
```
tree._ttreereader = ROOT.TTreeReader(tree, tree._entrylist)
TypeError: none of the 5 overloaded methods succeeded. Full details:
  TTreeReader::TTreeReader(TTree* tree, TEntryList* entryList = nullptr) =>
    TypeError: could not convert argument 2
  TTreeReader::TTreeReader(const char* keyname, TDirectory* dir, TEntryList* entryList = nullptr) =>
    TypeError: could not convert argument 1 (bad argument type for built-in operation)
  TTreeReader::TTreeReader(const TTreeReader&) =>
    TypeError: takes at most 1 arguments (2 given)
  TTreeReader::TTreeReader() =>
    TypeError: takes at most 0 arguments (2 given)
  TTreeReader::TTreeReader(const char* keyname, TEntryList* entryList = nullptr) =>
    TypeError: could not convert argument 1 (bad argument type for built-in operation)
```
I make it work after modifying [treeReaderArrayTools.py](https://github.com/cms-nanoAOD/nanoAOD-tools/blob/master/python/postprocessing/framework/treeReaderArrayTools.py)
```
tree._ttreereader = ROOT.TTreeReader(tree, tree._entrylist)
...
_ttreereader = ROOT.TTreeReader(tree, getattr(tree, '_entrylist', None))
```

to
```
tree._ttreereader = ROOT.TTreeReader(tree)
...
_ttreereader = ROOT.TTreeReader(tree)
```

Michael

**Comment by meisonlikesicecream** [comment]
I also noticed some errors when using python3 with the later CMSSW versions for modules puWeightProducer.py and btagSFProducer.py. In case anyone else stumbles upon this, I solved it by changing the following in [line 63 puWeightProducer.py](https://github.com/cms-nanoAOD/nanoAOD-tools/blob/master/python/postprocessing/modules/common/puWeightProducer.py#L63):
`hist.SetDirectory(None)`    to    `hist.SetDirectory(0)`

And [line 249 btagSFProducer.py](https://github.com/cms-nanoAOD/nanoAOD-tools/blob/master/python/postprocessing/modules/btv/btagSFProducer.py#L249):
`self.algo, os.path.join(self.inputFilePath, self.inputFileName))`   to   `self.algo, os.path.join(self.inputFilePath, self.inputFileName), True)`
