### ISSUE TITLE
Computation of PU weight wrong

### ISSUE THREAD

**Issue by ktht** [cms-nanoAOD/nanoAOD-tools#30]
From `python/postprocessing/examples/puWeightProducer.py` line [49](https://github.com/cms-nanoAOD/nanoAOD-tools/blob/139e8145b9a3c56da8c9de2467d9b838b36b83fe/python/postprocessing/examples/puWeightProducer.py#L49), [10](https://github.com/cms-nanoAOD/nanoAOD-tools/blob/139e8145b9a3c56da8c9de2467d9b838b36b83fe/python/postprocessing/examples/puWeightProducer.py#L10) and [28](https://github.com/cms-nanoAOD/nanoAOD-tools/blob/139e8145b9a3c56da8c9de2467d9b838b36b83fe/python/postprocessing/examples/puWeightProducer.py#L28) it looks like the member `histogram_` in [`WeightCalculatorFromHistogram`](https://github.com/cms-nanoAOD/nanoAOD-tools/blob/139e8145b9a3c56da8c9de2467d9b838b36b83fe/python/postprocessing/helpers/WeightCalculatorFromHistogram.cc#L34) is instantiated as the bin-by-bin ratio of MC to data (see lines [45](https://github.com/cms-nanoAOD/nanoAOD-tools/blob/139e8145b9a3c56da8c9de2467d9b838b36b83fe/python/postprocessing/helpers/WeightCalculatorFromHistogram.cc#L45) and [101](https://github.com/cms-nanoAOD/nanoAOD-tools/blob/139e8145b9a3c56da8c9de2467d9b838b36b83fe/python/postprocessing/helpers/WeightCalculatorFromHistogram.cc#L101) in `python/postprocessing/helpers/WeightCalculatorFromHistogram.cc`), but it should be the other way round (data over MC).

Either you swap arguments in line [91](https://github.com/cms-nanoAOD/nanoAOD-tools/blob/139e8145b9a3c56da8c9de2467d9b838b36b83fe/python/postprocessing/helpers/WeightCalculatorFromHistogram.cc#L91), swap `targetvals` with `vals` in line [101](https://github.com/cms-nanoAOD/nanoAOD-tools/blob/139e8145b9a3c56da8c9de2467d9b838b36b83fe/python/postprocessing/helpers/WeightCalculatorFromHistogram.cc#L101), or swap the arguments in line [49](https://github.com/cms-nanoAOD/nanoAOD-tools/blob/139e8145b9a3c56da8c9de2467d9b838b36b83fe/python/postprocessing/examples/puWeightProducer.py#L49) of `puWeightProducer.py`. Any of those proposals should work (but I tested only the latter solution).

**Comment by emanueledimarco** [comment]
indeed. I noticed, but fixed only in a private version. Will fix it, thanks.

**Comment by emanueledimarco** [comment]
@ktht PR #31 fixes it.
