### ISSUE TITLE
Typo in btagSFProducer

### ISSUE THREAD

**Issue by ktht** [cms-nanoAOD/nanoAOD-tools#33]
I believe there's a typo:
https://github.com/cms-nanoAOD/nanoAOD-tools/blob/7e661bf1e09f9d08541e445aedfdbd4cbbe83119/python/postprocessing/modules/btv/btagSFProducer.py#L200
Instead, it should be:
```python
            discr = "btagCSVV2"
```
(Sorry, didn't bother creating a PR for this.)

**Comment by veelken** [comment]
The bug is fixed in PR https://github.com/cms-nanoAOD/nanoAOD-tools/pull/46 . This issue can be closed now.
