### ISSUE TITLE
demo post-processor crab submission failing

### ISSUE THREAD

**Issue by scooperstein** [cms-nanoAOD/nanoAOD-tools#42]
I have tried to run the crab submission of the demo post-processor using the setup provided in nanoAOD-tools/crab. The only edit I made was in crab_cfg.py to crab.Data.outLFNDirBase and config.Site.storageSite to match my user space. I launch the demo via

crab submit crab_cfg.py

and all the jobs fail with exit code 10040  (failed to generate cmsRun cfg file at runtime). I am getting the same error in our implementation of a VH(bb) post-processor, which had previously been working. Could there have been some change in the crab setup that is now causing the jobs to fail? I so far have not been able to find anything useful from the crab output.

@arizzi

**Comment by arizzi** [comment]
can you try a more recent nanoaod sample ?
I think simply the file you loaded doesn't exist anymore... I'll update the example to a more recent dataset

**Comment by scooperstein** [comment]
Indeed the only problem was the input dataset, which had been deleted but was still on DAS. Just successfully ran the demo on one of the new centrally produced 2016 TT files. Thanks for your help.

**Comment by andreypz** [comment]
Hello,

I'm encountering the same problem: crab jobs fail with 10040 status.
I think I'm running on existing samples. For example, I tried:
`/DYJetsToLL_1J_TuneCP5_13TeV-amcatnloFXFX-pythia8/RunIIFall17NanoAOD-PU2017_12Apr2018_94X_mc2017_realistic_v14-v1/NANOAODSIM`,
`/DYJetsToLL_M-4to50_HT-200to400_TuneCP5_13TeV-madgraphMLM-pythia8/RunIIFall17NanoAOD-PU2017_12Apr2018_94X_mc2017_realistic_v14-v2/NANOAODSIM` and some others.
Is there any other issue I should be aware of?

**Comment by andreypz** [comment]
UPD: Never mind, the problem was caused by an earlier update of exampleModule.
Pull #103 should fix it.
