### ISSUE TITLE
update btagSF

### ISSUE THREAD

**Issue by veelken** [cms-nanoAOD/nanoAOD-tools#45]
Update https://github.com/cms-nanoAOD/nanoAOD-tools/blob/master/python/postprocessing/modules/btv/btagSFProducer.py and related .csv files with corrections to BTV POG recipe on twiki https://twiki.cern.ch/twiki/bin/view/CMS/BtagRecommendation94X .

I volunteer to start working on this if you agree.

**Comment by arizzi** [comment]
thanks. we should add new files, without replacing existing ones.
Ideally we should make things more configurable then they are (right now the tagger to filename association is hardcoded)

**Comment by veelken** [comment]
Hi Andrea,

can you confirm that the branch Jet_btagCMVA in the nanoAOD Ntuple corresponds to the DeepCSV tagger ?

**Comment by arizzi** [comment]
nope, DeepB is DeepCSV
https://github.com/cms-nanoAOD/cmssw/blob/master/PhysicsTools/NanoAOD/python/jets_cff.py#L130

**Comment by veelken** [comment]
The new b-tagging scale factors for 2017 ReReco data and RunIIFall17 MC are implemented in the PR https://github.com/cms-nanoAOD/nanoAOD-tools/pull/46 . I also made the name of the CSV file with the scale factors configurable. Note that the shape corrections ("iterativefit" method) is not provided by the BTV POG for the 2017 ReReco data and RunIIFall17 MC yet, so the branches Jet_btagSF_shape_* are all 1.0 at the moment (only the branches Jet_btagSF, Jet_btagSF_up, and Jet_btagSF_down are filled with "proper" values so far).
