### ISSUE TITLE
haddnano.py should also merge genEventCounters in Runs tree

### ISSUE THREAD

**Issue by scooperstein** [cms-nanoAOD/nanoAOD-tools#52]
The event counters in the "Runs" tree necessary to normalize the MC prediction to the data integrated luminosity are not summed by haddnano.py. Instead, it seems that the branch is just filled with the value from a particular input file. Therefore at the moment one cannot use the event counters in the Runs tree and has to either assume the number from DAS or infer the event count from somewhere else.

**Comment by arizzi** [comment]
do you have an example?

**Comment by scooperstein** [comment]
Sure if I just run a local post-processor, for example this one [1], on two input files I get two output files file1.root, file2.root. If then locally call haddnano.py

python haddnano.py out.root file1.root file2.root

I see that for example the value of the branch Runs->genEventCount in out.root is equal to the value in file1.root rather than the sum of file1.root and file2.root.

[1] https://github.com/scooperstein/vhbb-nano/blob/master/postproc_local.py

**Comment by gpetruc** [comment]
The implementation is supposed to just put all weight entries from *all*
the input files in the output run tree, which should make summing them
rather straightfoward in the analysis code using a single Draw command.
Are you sure in the output you are getting only one entry?

Giovanni

**Comment by scooperstein** [comment]
Hi @gpetruc,
In the example I mention above I see that in out.root there is only one entry in the Runs tree and the value of the genEventCount branch is just the value from file1.root. Sorry if I am misunderstanding the intended usage, but it seems to me like one therefore loses the information necessary to normalize the final output.

**Comment by arizzi** [comment]
I think there is an indent bug in haddnano.py

**Comment by arizzi** [comment]
can you try to unindent L60,61 of
https://github.com/cms-nanoAOD/nanoAOD-tools/blob/master/scripts/haddnano.py#L60

**Comment by scooperstein** [comment]
unindenting itself didn't quite work because it crashed when trying to call obj.Merge on the TObjString untagged in the files. However if I just add an "elif isTree:" protection is seems like it works, afterwards out.root has two entries in the Runs tree where each entry has for example "genEventCount" value corresponding to file1/2.root.

**Comment by arizzi** [comment]
can you make a PR with the fix?

**Comment by scooperstein** [comment]
https://github.com/cms-nanoAOD/nanoAOD-tools/pull/53/files this should do it

**Comment by arizzi** [comment]
I'm afraid this would not merge Events tree.

You probably unindented too much.. remove the elif and unident only by one level so that you are still protected by the if at line 40

**Comment by scooperstein** [comment]
I didn't actually unindent at all, I just changed the relevant if required to get to the obj.Merge() call so that it is just "isTree" instead of "isTree and GetName()=="Events". I updated the PR, please let me know if you would prefer it a different way than it is now. And sorry for the dumb bug before.

**Comment by arizzi** [comment]
ok this way should work 

please cross check that both Events and Run are properly merged now

**Comment by arizzi** [comment]
was this fixed? can we close?

**Comment by scooperstein** [comment]
yes https://github.com/cms-nanoAOD/nanoAOD-tools/pull/53/files fixed it

**Comment by mariadalfonso** [comment]
the issue has been fixed in 2018
