### ISSUE TITLE
Add capability to recalculate JEC's for both MC and data in post-processor

### ISSUE THREAD

**Issue by scooperstein** [cms-nanoAOD/nanoAOD-tools#55]
It would be very useful if for example in python/postprocessing/modules/jme/jetmetUncertainties.py there was an option to recalculate the JEC's.  That way if the JEC's are updated one could just rerun the post-processor instead of reproducing NanoAOD. This module would have to run on both MC and data, for data there would need to be some option such that only the nominal value is calculated and it does not attempt to add uncertainties.

**Comment by scooperstein** [comment]
Can someone who is more familiar please comment on whether this would be feasible? I am happy to work on it but not sure where to start. Does one need separate txt inputs and/or syntax for getting the nominal JEC's? I guess it is a different procedure for data and MC? @arizzi @veelken @rappoccio @ktht

**Comment by arizzi** [comment]
yes,I was discussing it yesterday with @gpetruc @peruzzim 
To do it properly we need to add the feature in the postprocessing fwk to update a branch.
This means that we need to copy the variable having clear control of the buffer address so that we can write on it.

**Comment by rappoccio** [comment]
I actually think we probably shouldn't do this. NANOAOD can be processed within a day or two, so it's really not going to save time in the long run.

**Comment by arizzi** [comment]
mhh it sounds strange that we can recompute all systematic variations but not update the central value..

NanoAOD can be remade but it doesn't mean we *have  to* remake them each time we want to change a comma

**Comment by rappoccio** [comment]
Well, it's more that you HAVE to recompute the systematic variations for many/most analyses. It will cause a lot of confusion to have this, because there isn't really a way for people to see what JECs have been applied to the given branches in any easy way (for instance, in MINIAOD the EDM products will have a different name). 

I dunno. If people feel strongly then it's fine to have them in.

**Comment by arizzi** [comment]
I'm not sure I understood..

Il gio 15 mar 2018, 14:47 rappoccio <notifications@github.com> ha scritto:

**Comment by rappoccio** [comment]
We don't store, say, the JEC uncertainty sources so they *have* to be recomputed on the fly.

**Comment by arizzi** [comment]
right, they anyhow have to be computed... I mean there is nothing stored in nanoaod that uses the JEC uncertainties.. so if you need them you have to compute them.
Nanoaod only have the nominal JEC applied, given that you have to anyhow compute yourself all the variations it make sense to have the option to, at the same time, update the nominal value

**Comment by rappoccio** [comment]
What variations do you mean?

**Comment by arizzi** [comment]
variations = 26 independent sources of systematic uncertainties

**Comment by rappoccio** [comment]
Right, but those aren't an alternative to the nominal value, those are the uncertainties IN the nominal value, broken by source.

**Comment by arizzi** [comment]
I'm not sure I appreciate a difference, let say
with JEC v3
nominal correction for a given jet  is 1.15,  systematic12_up 1.17, systematic12_down is 1.13
with JEC v4
nominal correction for a given jet  is 1.25,  systematic12_up 1.27, systematic12_down is 1.23

so if you have to recompute 1.17 and 1.13 you can also recompute the nominal...

**Comment by rappoccio** [comment]
The systematics up and down are given relative to the nominal.

**Comment by arizzi** [comment]
the systematics up and down are NOT stored, they are loaded from a file and as long as you read the consistent file for the central value and the systematics there is no difference... really I do not understand what your point is... 

we are in the position of recomputing the central value of the JEC and it is the same operational cost of one of the N systematic variation, it is even done with the same code... so what's the problem in actually doing it?

**Comment by rappoccio** [comment]
OK I see what you are saying. It does come at the same computational cost. 

I was talking more along the lines of robustness and simplicity. If the user reapplies the JECs in this way, it is basically invisible downstream. That's not necessarily a show-stopper, though.

**Comment by arizzi** [comment]
#58 implemented it
