### ISSUE TITLE
jetmetUncertainties.py references gen collection not present in 2016 MC

### ISSUE THREAD

**Issue by scooperstein** [cms-nanoAOD/nanoAOD-tools#60]
Hi,

If one calls the jetmetUncertainties producer for AK08 jets while running on 2016 MC the post-processor fails here when trying access the collection referenced here [1]. As far as I can tell this does not exist in the 2016 MC NanoAOD ntuples.

[1] https://github.com/cms-nanoAOD/nanoAOD-tools/blob/master/python/postprocessing/modules/jme/jetmetUncertainties.py#L38

**Comment by arizzi** [comment]
@rappoccio  can you comment?

**Comment by rappoccio** [comment]
Correct, they do not exist in the previous MINIAOD so we don't have them in NANOAOD. People would have to run their own.

**Comment by arizzi** [comment]
can't we make them at NANO time? would it be too slow?
people cannot make them on their own from nanoaod I guess

**Comment by rappoccio** [comment]
They cannot make them from NANOAOD. In principle a workflow could be done to compute them at NANOAOD time, but I thought these would eventually be re-done with the new MINIAOD?

**Comment by arizzi** [comment]
some samples of 80X do not exist in AOD format so they will not be produced in reminiaod, if using the gensubjets is the only way to properly smear the fatjet mass then I guess we  should support doing it at nanotime

**Comment by arizzi** [comment]
#78 fixes it
