### ISSUE TITLE
overwrite branches with same name

### ISSUE THREAD

**Issue by ashrafkasem** [cms-nanoAOD/nanoAOD-tools#81]
Hi, is there any way to overwrite a branch with the same name 

for example if i have run several modules and i realized that some branches filled incorrectly so i can run again but to fill only those branches instead of running from the beginning. 
i tried but if the branch is already exist in the input file i got error of 
" *** Break *** segmentation violation"

is there any workaround ? 

Cheers
Ashraf

**Comment by arizzi** [comment]
#57 should have introduced this possibility

perhaps @lenzip can help you in case you have problem with it.... @lenzip can we write an example in the workbook https://twiki.cern.ch/twiki/bin/view/CMSPublic/WorkBookNanoAOD ?

**Comment by lenzip** [comment]
My PR actually does not seem to work properly I can only overwite the 
last branch written. I'm working on a fix, I can probably make a PR 
later today.
Giulio

**Comment by arizzi** [comment]
@ashrafkasem  can you try #84 and confirm it works for you too?

**Comment by lenzip** [comment]
The usage is simply that you have to declare the branch as you would 
normally do for a new branch.

**Comment by arizzi** [comment]
@lenzip can you clarify if modules later in the sequence can access the information, and if so how? I think it may not be obvious is modules downstream should still see the original or the updated information

**Comment by ashrafkasem** [comment]
I've tried #84 it looks for me that it works but it does not overwrite the existing branch, it just leave it as it is

**Comment by lenzip** [comment]
That is strange I've tested it multiple times.
Can you give me an example?
Giulio

**Comment by ashrafkasem** [comment]
for examples in the file root://cms-xrd-global.cern.ch//store/user/amohamed/METRun2016Bver1.root
I've filled the branch named "PD_MET" incorrectly and when I rerun it's still unchanged. 
for double check, I filled a new branch with a different name but with the same value and it filled correctly 
looks like the old branch kept the same 

Ashraf

**Comment by ashrafkasem** [comment]
for example the attached module 
[new.py.zip](https://github.com/cms-nanoAOD/nanoAOD-tools/files/1974575/new.py.zip)

**Comment by ashrafkasem** [comment]
okay, it's my mistake. I realized that I was trying to overwrite a branch of type float with boolean so I changed back the type to float and indeed to works. 

sorry for misstating now it works fine with me 

thanks a lot 

Ashraf Mohamed

**Comment by lenzip** [comment]
perfect thanks!

**Comment by arizzi** [comment]
can you guys write some docs about it in the nanoaod workbook?

**Comment by ashrafkasem** [comment]
yeah, I can do it 

Ashraf

**Comment by ashrafkasem** [comment]
https://twiki.cern.ch/twiki/bin/view/CMSPublic/WorkBookNanoAOD#More_information
