### ISSUE TITLE
Gen_Part information 

### ISSUE THREAD

**Issue by ashrafkasem** [cms-nanoAOD/nanoAOD-tools#88]
Hi, 

Do you know any trick to get the information about mother and grandmother of a certain particle? 

Cheers
Ashraf

**Comment by gpetruc** [comment]
The GenPart_genPartIdxMother gives you the index to the mother of the particle.

**Comment by gpetruc** [comment]
`GenPart_genPartIdxMother[GenPart_genPartIdxMother[i]]`

**Comment by ashrafkasem** [comment]
awesome worked, thanks a lot 

Cheers
Ashraf
