### ISSUE TITLE
Variable 'nall' referenced before assignment in postprocessor.py

### ISSUE THREAD

**Issue by lcorcodilos** [cms-nanoAOD/nanoAOD-tools#95]
Hello,

I came across what I believe is a bug in postprocessor.py. On[ lines 128-141](https://github.com/cms-nanoAOD/nanoAOD-tools/blob/master/python/postprocessing/framework/postprocessor.py#L128-L141), the variable 'nall' is only assigned `if not FullClone` but it's called `if self.jobReport`. I'm not running any modules but I do request a job report so 'nall' is never assigned.

I'm not sure whether 'nall' needs assigning or it makes no sense to have a job report for a full clone.

Thanks!
Lucas

**Comment by gpetruc** [comment]
Hi,

I suppose it should be set to the number of entries in the input tree in
the else branch.
Can you make a PR?
Thanks,

Giovanni


Il Mar 10 Lug 2018, 18:27 lcorcodilos <notifications@github.com> ha scritto:

**Comment by lcorcodilos** [comment]
Done. Let me know if there are any issues.
